name: Update CV

on:	
  push:	
    branches: [ master ]	
jobs:	
  build_latex:	
    runs-on: ubuntu-latest	
    steps:	
      - name: Repository Dispatch	
        uses: peter-evans/repository-dispatch@v1	
        with:	
          token: ${{ secrets.REPO_ACCESS_TOKEN }}	
          repository: sharadmv/sharadvikram.com	
          event-type: update-cv
